<?= $this->doctype(); // выводим doctype: <!DOCTYPE html>
$this->layout()->searchform = new Form_Search();
?> 
<html>
    <head>
        <?
        // выводим тег <title>
        echo $this->headTitle(); 
        
        // выводим мета-теги
        echo $this->headMeta();
        
        // выводим яваскрипты
        echo $this->headScript();
        
        // выводим css фалы
        echo $this->headLink();
        ?>
    </head>
    <body>
        <div class="container">
            <div class="header">

            </div>
            <div class="navbar">
                <div class="navbar-inner">
                    <div class="container" style="width: auto">
                        <a class="brand" href="/">
                            SmallCMS
                        </a>
                        <div class="nav-collapse">
                            <!-- выводим главное меню -->
                            <?= $this->layout()->nav ?>
                            
                            <!-- выводим форму поиска -->
                            <?= $this->layout()->searchform ?>
                        </div>
                    </div>
                </div>
            </div>
            <div class="span4">
                <div class="well" style="padding: 8px 0">
                    <!-- выводим меню пользователя -->
                    <?= $this->layout()->userMenu ?>
                </div>
            </div>
            <div class="container">
                <div class="content span7">
                    <?= $this->layout()->content; // здесь будет автоматичеки выводиться содержимое скриптов вида?>
                </div>
            </div>
            <hr/>
            <div class="footer">
                © SmallCMS <?= date('Y') ?>
                <div class="footer-menu">
                    <!-- выводим футер меню -->
                    <?= $this->layout()->footerMenu ?>
                </div>
            </div>
        </div>
    </body>
</html>