<?= $this->doctype(); // выводим doctype: <!DOCTYPE html>
$this->layout()->searchform = new Form_Search();
$auth = Zend_Auth::getInstance();
?> 
<html>
    <head>
        <?
        // выводим тег <title>
        echo $this->headTitle(); 
        
        // выводим мета-теги
        echo $this->headMeta();
        
        // выводим яваскрипты
        echo $this->headScript();
        
        // выводим css фалы
        echo $this->headLink();
        ?>
    </head>
    <body>
        <div class="container">
            <div class="header">

            </div>
            <div class="navbar">
                <div class="navbar-inner">
                    <div class="container" style="width: auto">
                        <a class="brand" href="/">
                            SmallCMS
                        </a>
                        <div class="nav-collapse">
                            <!-- выводим главное меню -->
                            <?= $this->menu('top', 'default') ?>
                            
                            <!-- выводим форму поиска -->
                            <?= $this->layout()->searchform ?>
                            <ul class="nav pull-right">
                                <li class="divider-vertical"></li>
                                <? if ($auth->hasIdentity()){?>
                                    <li>
                                        <a href="<?= $auth->getIdentity()->role == 'admin'? '/admin/' : ''  ?>" title="My Profile">
                                            <?= (!empty($auth->getIdentity()->first_name))? 
                                                $auth->getIdentity()->first_name : $auth->getIdentity()->email ?>
                                        </a>
                                    </li>
                                    <li><a href="<?= $this->url(array(), 'user-logout') ?>">Logout</a></li>
                                <? }else{ ?>
                                    <li><a href="<?= $this->url(array(), 'user-login') ?>" id="login">Login</a></li>
                                <? } ?>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <? if(!$auth->hasIdentity()){?>
            <div id="auth-form">
                <div class="loading"></div>
                <?= new Form_Login(array('ajax' => 'true'))?>
            </div>
            <? } ?>
            <? if (!empty($this->layout()->message)){ ?>
                <div class="alert <?= $this->layout()->message_class ?>">
                    <a class="close" data-dismiss="alert">×</a>
                    <?= $this->layout()->message ?>
                </div>
            <? } ?>
            <div class="span3">
                <div class="well" style="padding: 8px 0">
                    <!-- выводим меню пользователя -->
                    <?= $this->menu('left', 'default') ?>
                </div>
            </div>
            <div class="container main-content">
                <div class="content span8">
                    <?= $this->layout()->content; // здесь будет автоматичеки выводиться содержимое скриптов вида?>
                </div>
            </div>
            <hr/>
            <div class="footer">
              © SmallCMS <?= date('Y') ?> [<a href="http://instanceof.org">instanceof.org</a>]
                <div class="footer-menu">
                    <!-- выводим футер меню -->
                    <?= $this->layout()->footerMenu ?>
                </div>
            </div>
        </div>
    </body>
</html>